services:
  db:
    image: postgres:15
    restart: always
    hostname: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: $PGDATA
    volumes:
      - db:$PGDATA
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_USER: $DB_USER
      DB_HOST: $DB_HOST
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
      POSTGRESQL_URL: $POSTGRESQL_URL
      FLASK_APP: $FLASK_APP
      FLASK_DEBUG: $FLASK_DEBUG
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4:8.5
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_CONFIG_SERVER_MODE: $PGADMIN_CONFIG_SERVER_MODE
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db
volumes:
  db: